cache:
  bundler: true
  yarn: true
services:
- redis-server
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install google-chrome-stable
- nvm install --lts
addons:
  postgresql: '9.6'
before_script:
- psql -c 'create database pharm_price_checker_test;' -U postgres
script:
- bundle exec rake db:schema:load
- bundle exec rake db:test:prepare
- SECRET_KEY_BASE=a RAILS_ENV=production bundle exec rake assets:precompile
- bundle exec rake test
- bundle exec rake test:system
env:
  global:
    secure: F3sB+cjSEnRU5H/j2pVgPUbsoi99JJmTPAxoYt1uuYhB3D+4pvqnOI2MY1zG/SMD5tKjFdea7rBpNiWW9ASouic4k7hJe/ZWrtxxw7dGK/eQs1A7hNVWhrISSqMsmsQcqiaEuvYLngovOIby/5GijidW4FIwosAResbWbFQV8X95sdmei+AoPTqe23riMgMa7qcBXNS5ew3sraly400B0UhAg6bnaTSpX47JuK6D5WgGMuBjs0Duma4Yng1UNWpWVB7r/kSARZs94jf0qIzITTEtPTFSahwkqAjluF4eLzPWExcaLVnfqzpFY4MnAkjFvX5p40bd2FCnxWlS6twqblOXs1VvUCW2ohgzCXEUDUONL9laD6HjNcIv681+26gNgrK4gyCClkMM3qLiAx7b7s3WzBIw06xTFjYiGCn1uFkCetmZA5ofOtk+f3k+dQ10CUMwJurR2sumpTtSXQ1Hxr4kCC5QXiujBcYNDBOYDchYCeE7Mpi/hD8oloUDNnrhxFcEXAeKa+GAIN9XwRX9TagC0mWDPIV2mDZ6uSzDgr5yLKiKyIJBCM4/ri/stpPB3oz9TFU2nNGeYAvSuRh67YbWFW1+ZWjVX8xfeHKpAx6WMnNIvkxzfrisW7VhbFwhX55B6VIym9imctpJSj5nwZBm6hdOVNZLw0IZUwGopp4=
